# Generated by Django 4.1.5 on 2023-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCaisse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetraitCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("motif", models.TextField()),
            ],
        ),
    ]
