# Generated by Django 4.1.5 on 2023-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCaisse", "0002_retraitcaisse"),
    ]

    operations = [
        migrations.AddField(
            model_name="retraitcaisse",
            name="caisse",
            field=models.CharField(default="Secretariat", max_length=100),
        ),
    ]
