# Generated by Django 4.1.5 on 2023-10-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCaisse", "0003_retraitcaisse_caisse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultatCalcul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.DateField()),
                ("caisse", models.CharField(max_length=100)),
                (
                    "somme_disponible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
